### ISSUE TITLE
Seems to get confused by "Python [default]" kernel name

### ISSUE THREAD

**Issue by ijstokes** [Anaconda-Server/nb_conda#13]
See screenshot below.  The in-notebook-editor package editor should be getting the conda environment path (in this case "default") from somewhere other than the kernel name (in this case "Python [default]").

<img width="694" alt="screenshot 2016-03-02 01 36 20" src="https://cloud.githubusercontent.com/assets/293525/13452627/9975f274-e017-11e5-86f9-03c65bf495d0.png">

**Comment by mmarchetti** [comment]
https://github.com/Anaconda-Server/nb_conda/pull/14

**Comment by damianavila** [comment]
#14 was merged, let's close this one.
