### ISSUE TITLE
#conda in URL isn't sufficient to open page on conda tab

### ISSUE THREAD

**Issue by ijstokes** [Anaconda-Server/nb_conda#15]
For the tree.js file viewer, the #conda URL mark doesn't cause the page to open at the conda tab.  I think this might be an effect of the way the conda tab appears to get automatically patched in to the DOM by the JS, so perhaps the #conda page anchor doesn't actually exist when the page is first loaded.  But it means that we can't provide URLs that navigate directly to the Conda tab in the file view, and that is one awesome piece of work I think we should have the ability to get to directly by URL.

**Comment by mmarchetti** [comment]
I think we could do this by inspecting the url hash when we load the extension, and popping the tab to the front if the hash is #conda.

**Comment by mmarchetti** [comment]
https://github.com/Anaconda-Server/nb_conda/pull/16

**Comment by damianavila** [comment]
#16 was merged, so closing this one.
