### ISSUE TITLE
Incomplete regex for pulling out env name of nb_conda_kernels

### ISSUE THREAD

**Issue by bollwyvl** [Anaconda-Server/nb_conda#19]
This [line](https://github.com/Anaconda-Server/nb_conda/blob/master/nb_conda/nbextension/static/main.js#L68):
```javascript
 m = /\[(\w+)\]/.exec(kernel_name);
```
has two things going on:
- it's a naked assignment, which gets hoisted all the way to the global scope, clobbering any other `m` variable.
  - I don't know if any libraries use that, but they could.
  - possible fixes:
    - [ ] fix with `var`
    - [ ] fix better with `use strict` at top of `define`d function
      - [ ] fix process by adding a linting step
- the regex uses `\w`, 

  > any alphanumeric character from the basic Latin alphabet, including the underscore. Equivalent to [A-Za-z0-9_].

  but conda can pretty much use anything in an env name, including square brackets and spaces (if you hate yourself... though things start breaking IMMEDIATELY, then)... but we can only do so much here
  - [ ] fix by accepting everything but a trailing square bracket: `\[(.+)\]$`

I'll work up a `[wip]`.

**Comment by damianavila** [comment]
Closed by #20
